[package]
name = "encrypt_internal"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_box = { version = "0.9.1", features = ["chacha20"] }
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"] }
