[package]
name = "prontus"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[workspace]
members = ["crates/client", "crates/pusher"]

[dependencies]
client = { path = "crates/client" }
gpui = { git = "https://github.com/zed-industries/zed" }

[profile.release]
debug = 1
