[package]
name = "client_macros"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = "0.1.0"


[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
