[package]
name = "ui-macros"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
