[package]
name = "probot"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../client" }
pusher = { path = "../pusher" }
log = "0.4.22"

[dev-dependencies]
tokio = { workspace = true }
