[package]
name = "encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
blake3 = "1.5.5"
encrypt_internal = { path = "../encrypt-internal" }
reqwest = { workspace = true }
serde = { workspace = true }
