[workspace]
members = ["client", "client_macros", "encrypt", "encrypt-internal", "extension", "extension-api", "probot", "pusher", "search", "settings", "ui_handlers", "ui_lib", "ui_macros"]
resolver = "2"

[workspace.dependencies]
log = "0.4"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
