[workspace]
members = ["client", "client-macros", "encrypt", "encrypt-internal", "extension", "extension-api", "extension-cli", "probot", "pusher", "search", "settings", "ui-handlers", "ui-lib", "ui-macros", "updater", "version", "wit-gen"]
resolver = "2"

[workspace.dependencies]
futures = "0.3"
log = "0.4"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = "0.14"
thiserror = "2"
tokio = { version = "1.42", features = ["full"] }
wit-bindgen = "0.36.0"
wasmtime = "28"
wasmtime-wasi = "28"
wasmparser = "0.222"
wasm-encoder = "0.222"
wit-component = "0.222"
