[package]
name = "extension"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../client" }
log = { workspace = true }
rayon = "1.10.0"
serde = { workspace = true }
settings = { path = "../settings" }
thiserror = { workspace = true }
toml = "0.8"
wasmtime = "26"
wasmtime-wasi = "26"
wit-bindgen = "0.35"
