import { Button, HorizontalBox, ScrollView, VerticalBox } from "std-widgets.slint";
import { Message, MessageComponent } from "message.slint";
import { Channel, ChannelGroup, Sidebar } from "sidebar.slint";

export component AppWindow inherits Window {
    in-out property <string> fullname: "";
    in-out property <[ChannelGroup]> channels <=> side-bar.model;
    out property <int> current_sidebar_item_id <=> side-bar.current-item;
    in-out property <[Message]> messages;
    out property <length> visible_height <=> scroll-view.visible-height;
    in-out property <length> viewport_y <=> scroll-view.viewport-y;
    out property <length> viewport_height <=> scroll-view.viewport-height;
    in-out property <int> top_msg_id;
    in-out property <int> channel_id;

    callback setChannel <=> side-bar.on-change;
    callback scrollChannel();

    HorizontalLayout {
        side-bar := Sidebar {
            title: "Prontus";
        }
        VerticalBox {
            scroll-view := ScrollView { // TODO: limit width
                VerticalLayout {
                    for message in messages:MessageComponent  {
                        message: message;
                    }
                }
//                HorizontalLayout {
//                    TextInput {
//                    }
//                    Button {
//                        text: "Send";
//                    }
//                }
                area := TouchArea {
                    width: parent.width;
                    height: parent.height;
                    scroll-event(e) => {
                        scrollChannel();
                        EventResult.accept
                    }
                }
            }
        }
    }
}
