// TODO: Boxes instead of layouts

import { Button, HorizontalBox, ScrollView, VerticalBox } from "std-widgets.slint";
import { Message, MessageComponent } from "message.slint";
import { Channel, ChannelGroup, Sidebar } from "sidebar.slint";

export component AppWindow inherits Window {
    title: "Prontus";
    min-height: 500px;
    min-width: 750px;
    in-out property <[ChannelGroup]> channels <=> side-bar.model;
    out property <int> current_sidebar_item_id <=> side-bar.current-item;
    in-out property <[Message]> messages;
    out property <length> visible_height <=> scroll-view.visible-height;
    in-out property <length> viewport_y <=> scroll-view.viewport-y;
    out property <length> viewport_height <=> scroll-view.viewport-height;
    in-out property <int> top_msg_id;
    in-out property <int> channel_id;
    in-out property <string> message <=> send-box.text;

    callback setChannel <=> side-bar.on-change;
    callback scrollChannel();
    callback sendMessage <=> send-box.accepted;
    callback deleteMessage(int);


    HorizontalLayout {
        side-bar := Sidebar {
            title: "Prontus";
        }
        VerticalLayout {
            VerticalBox {
                scroll-view := ScrollView {
                    area := TouchArea {
                        width: parent.width;
                        height: parent.height;
                        x: 0px;
                        y: 0px;
                        scroll-event(e) => {
                            scrollChannel();
                            if (parent.viewport-y < -20px) { // TODO: Obviously hacky and needs to be replaced with proper values at the very least
                                parent.viewport-y += 20px;
                            } else if (parent.viewport-y < 0px) {
                                parent.viewport-y = 0;
                            }
                            EventResult.accept
                        }
                    }
                    VerticalLayout {
                        x: 0px;
                        y: 0px;
                        max-width: root.width - 255px; // TODO: Another hack
                        for message in messages:MessageComponent  {
                            m-width: root.width - 255px;
                            message: message;
                            delete(id) => {deleteMessage(id)}
                        }
                    }
                }
            }
            HorizontalLayout {
                padding-left: 25px;
                send-box := TextInput { // TODO: Focus on channel switch
                    height: 50px;
                    font-size: 16px;
                }
            }
        }
    }
}
