import { VerticalBox } from "std-widgets.slint";

export struct Embed {
    title: string,
    link: string,
    description: string
}

export component EmbedComponent inherits Rectangle {
    in property <Embed> embed: {
        title: "Test Embed",
        link: "https://example.com",
        description: "This is some example text that goes on and on and on and on"
    };

    in property <length> m-width: 250px;

    border-radius: 5px;
    border-width: 1px;
    border-color: grey;

    callback clicked <=> touch.clicked;

    states [
        pressed when touch.pressed : {
            state.opacity: 0.8;
        }
        hover when touch.has-hover : {
            state.opacity: 0.6;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: grey;

        animate opacity { duration: 150ms; }
    }

    VerticalBox {
        Text {
            text: embed.link;
            font-size: 11px;
            width: root.m-width - 30px;
            overflow: TextOverflow.elide;
        }
        Text {
            text: embed.title;
            font-size: 15px;
        }
        Text {
            text: embed.description;
            wrap: word-wrap;
            width: root.m-width - 30px;
        }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}
