import { Button } from "std-widgets.slint";

export struct Reaction {
    id: int,
    user_ids: [int],
    checked: bool
}

export component ReactionComponent inherits Button {
    in property <Reaction> reaction;
    callback changed(int, bool);
    checkable: true;
    text: reaction.user_ids.length;
    colorize-icon: false;
    max-width: 50px;
    checked: reaction.checked;
    clicked => {root.changed(reaction.id, root.checked)}
    init => {
        if (reaction.id == 1) {
            self.icon = @image-url("assets/thumbs-up.png");
        }
        if (reaction.id == 2) {
            self.icon = @image-url("assets/thumbs-down.png");
        }
        if (reaction.id == 3) {
            self.icon = @image-url("assets/laugh.png");
        }
        if (reaction.id == 4) {
            self.icon = @image-url("assets/love.png");
        }
        if (reaction.id == 5) {
            self.icon = @image-url("assets/cry.png");
        }
        if (reaction.id == 6) {
            self.icon = @image-url("assets/amazed.png");
        }
    }
}
