import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

export struct Channel {
    id: int,
    title: string,
    unread: bool,
    notifications: int,
    can_send_message: bool,
    // TODO: can_send_message etc.
}

export struct ChannelGroup {
    id: int,
    title: string,
    channels: [Channel]
}

export component SidebarItem inherits Rectangle {
    in property <bool> selected;
    in property <bool> has-focus;
    in property <bool> unread;

    in-out property <string> text <=> label.text;

    callback clicked <=> touch.clicked;

    min-height: l.preferred-height;

    states [
        pressed when touch.pressed : {
            state.opacity: 0.8;
        }
        hover when touch.has-hover : {
            state.opacity: 0.6;
        }
        selected when root.selected : {
            state.opacity: 1;
        }
        focused when root.has-focus : {
            state.opacity: 0.8;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: #ac0000;

        animate opacity { duration: 150ms; }
    }

    l := HorizontalBox {
        y: (parent.height - self.height) / 2;
        spacing: 0px;

        label := Text {
            color: white;
            vertical-alignment: center;
            width: 225px; // TODO: no hardcoding
            overflow: TextOverflow.elide;
         }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}


export component Sidebar inherits Rectangle {
    in property <[ChannelGroup]> model: [];
    in property <string> name;
    out property <int> current-item: 0;
    out property <Channel> current-channel;
    out property <int> current-focused: -1; // The currently focused tab

    callback on-change(Channel);

    width: 250px;
    accessible-role: tab;

    Rectangle {
        background: #911b1f;
    }

    VerticalBox {
        padding-left: 0px;
        padding-right: 0px;
        alignment: start;

        navigation := VerticalLayout {
            alignment: start;
            vertical-stretch: 0;
            HorizontalBox {
                padding-top: 10px;
                padding-bottom: 10px;
                padding-left: 25px;
                Text {
                    text: name;
                    color: white;
                    font-size: 18px;
                }
            }
            for category in root.model : VerticalLayout {
                HorizontalBox {
                    Text {
                        text: category.title;
                        color: white;
                        overflow: TextOverflow.elide;
                        font-size: 15px;
                        padding-left: 25px;
                    }
                }
                for item in category.channels : SidebarItem {
                    clicked => {
                        root.current-item = item.id;
                        root.current-channel = item;
                        on-change(root.current-channel);
                    }
                    has-focus: item.id == root.current-focused;
                    text: item.title;
                    selected: item.id == root.current-item;
                }
            }
        }

        VerticalLayout {
            bottom := VerticalBox {
                padding-top: 0px;
                padding-bottom: 0px;

                @children
             }
        }
    }
}
