name: Builds

on:
  push:
    branches: [ "master", "stable" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-13", "macos-latest" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        rustflags: ""

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build
        run: cd ui && npm install && npm run tauri build

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus.exe (amd64)
          path: "./ui/src-tauri/target/release/ui.exe"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus_0.1.0_x64_en-US.msi
          path: "./ui/src-tauri/target/release/bundle/msi/prontus_0.1.0_x64_en-US.msi"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus_0.1.0_x64-setup.exe
          path: "./ui/src-tauri/target/release/bundle/nsis/prontus_0.1.0_x64-setup.exe"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: prontus_0.1.0_amd64.deb
          path: ./ui/src-tauri/target/release/bundle/deb/prontus_0.1.0_amd64.deb
    
      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: prontus-0.1.0-1.x86_64.rpm
          path: ./ui/src-tauri/target/release/bundle/rpm/prontus-0.1.0-1.x86_64.rpm
      
      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: prontus_0.1.0_amd64.AppImage
          path: ./ui/src-tauri/target/release/bundle/appimage/prontus_0.1.0_amd64.AppImage

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos-13')
        with:
          name: Prontus.app (amd64)
          path: ./ui/src-tauri/target/release/bundle/macos/prontus.app

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos-13')
        with:
          name: prontus_0.1.0_x64.dmg
          path: ./ui/src-tauri/target/release/bundle/dmg/prontus_0.1.0_x64.dmg

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos-latest')
        with:
          name: Prontus.app (aarch64)
          path: ./ui/src-tauri/target/release/bundle/macos/prontus.app

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos-latest')
        with:
          name: prontus_0.1.0_aarch64.dmg
          path: ./ui/src-tauri/target/release/bundle/dmg/prontus_0.1.0_aarch64.dmg
